services:

  mongodb:
    build: mongodb/
    image: mongohaslinger
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/mongodb/data

    networks:
      - backend
  server:
    build: backend/
    image: asozialesnetzwerkserver
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - pgadmindata:/var/lib/server
    depends_on:
      - mongodb
      
   

    networks:
      - backend
    
        
networks:
  backend:

volumes:
  pgdata:
  pgadmindata:
   